### ISSUE TITLE
re-insert missing part to documentation

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/doc_jumpscale8#5]
reinsert docu

**Comment by despiegk** [comment]
reinsert other docu items, check & fix the content
![image](https://cloud.githubusercontent.com/assets/6021844/15918492/432e51f0-2e18-11e6-941c-063571d052fd.png)

**Comment by despiegk** [comment]
other ones
https://github.com/Jumpscale/docs8/commit/5dab57e7941a7c0ad5cbebb3d9e699986ce7763f#diff-b4f3573b2f24d5af026c33acf52ff716

**Comment by ahussein** [comment]
https://github.com/Jumpscale/doc_jumpscale8/pull/21
