### ISSUE TITLE
restore content from before

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/doc_jumpscale8#6]
look at
https://github.com/Jumpscale/docs8/blob/ff4b6bccc9c8b1b305428c4b7931b3bf28b410b2/SUMMARY.md

90+% of content was usable
restore asap

K.

**Comment by ahussein** [comment]
Everything that was removed is ether broken links or links that contain instructions that are not  working anymore.

**Comment by ahussein** [comment]
https://github.com/Jumpscale/doc_jumpscale8/pull/21
